version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nix"
    open-pull-requests-limit: 1
    directory: "/"
    groups:
      nix-flake:
        patterns:
          - "*"
    schedule:
      interval: "cron"
      cronjob: "9 15 * * 3"
