version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nix"
    open-pull-requests-limit: 30
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "17 15 * * 3"
