keys:
  - &mark age1kvqdky620vtl2y2an4v20ssag55z7rz76scg2mr54nqlena4ydus7yydjm
  - &zeno age148e7mutxgyglf3q27qtah6lsup3qkgewngqk7uj95j7a2lxg3ywswmaf2q
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *mark
        - *zeno
