keys:
  - &mark age1kvqdky620vtl2y2an4v20ssag55z7rz76scg2mr54nqlena4ydus7yydjm
  - &zeno age148e7mutxgyglf3q27qtah6lsup3qkgewngqk7uj95j7a2lxg3ywswmaf2q
  - &aurele age1en0ulzh3krmxn3r3a8jlxmc6edszv7f08jvvvuwtlcafqacr9yhqfxzymr
creation_rules:
  - path_regex: secrets/mark/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *mark
        - *zeno
  - path_regex: secrets/aurele/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *aurele
        - *zeno
  - path_regex: secrets/zeno/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *zeno
